post/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    # post views
    path('', views.welcome, name='welcome'),
    path('home/', views.post_list, name='home'),
    path('<int:user_id>/wall/', views.post_list, name='wall'),
    path('<int:post_id>/', views.post_detail,name='post_detail'),
   
    #path('all/', views.post_list, name='post_list'),
    # path('writers-space/', views.post_list, name='post_list_author'),
    # path('category/<slug:category_slug>/', views.post_list, name='post_list_by_category'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    
    path('create/', views.create_post, name='create_post'),

    
    path('<int:post_id>/update/', views.update_post, name='update_post'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/<int:comment_id>', views.post_detail,name='comment'), # added this to be able to use comment get_asolute_url
    path('<int:post_id>/<int:comment_id>/update_comment', views.update_comment,name='update_comment'),
    path('<int:post_id>/<int:comment_id>/delete_comment', views.delete_comment,name='delete_comment'),
    path('search/', views.search, name='search'),
    # path('contact/', views.contact, name='contact'),manage_friends
    path('edit/', views.edit, name='edit'),
    #path('profile/', views.profile, name='profile'),
    path('invite/', views.send_invitation, name='send_invitation'),
    path('unfriend/', views.unfriend, name='unfriend'),
    path('accept/', views.accept, name='accept'),
    path('reject/', views.reject, name='reject'),
    path('cancel/', views.cancel, name='cancel'),


]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from post import views





urlpatterns = [
    path('register/',views.register,name='registration'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(),name='logout'),
    # change password urls
    path('accounts/password_change/',auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),name='password_change_done'),
    # reset password urls
    path('accounts/password_reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html' ),name='password_reset'),
    path('accounts/password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html' ),name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('accounts/reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('accounts/', include('django.contrib.auth.urls')),


    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
  

post/forms.py
from django import forms
#from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Comment, Post, User

from django.core.exceptions import ValidationError


class UserCreationEmailForm(UserCreationForm):
    email = forms.EmailField()
    username = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    def clean(self):
        email=self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('Email already exists! try another one.')
        username=self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError('Username already exists! try another one.')

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name',)

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email')

# class ContactForm(forms.Form):
#     subject = forms.CharField(max_length=50, required=True)
#     name = forms.CharField(max_length=20, required=True)
#     from_email = forms.EmailField(max_length=50, required=True)
#     message = forms.CharField(max_length=500,widget=forms.Textarea(),help_text='Write here your message!')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text','image','video','url',)



# class SearchForm(forms.Form):
#     query = forms.CharField(label=False,widget=forms.TextInput(attrs=dict(placeholder=(" hit enter to search"))))

post/views.py
#from django.dispatch.dispatcher import receiver
from django.shortcuts import redirect, render, get_object_or_404, redirect
from django.urls import reverse_lazy

from .models import Post, Comment, Profile, Relationship

from django.contrib.auth.models import Group, User
from django.contrib.auth import authenticate, login


# ContactForm, SearchForm
from .forms import UserCreationEmailForm, PostForm, CommentForm, UserEditForm
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


# from django.db.models import Count

# from django.core.mail import send_mail, EmailMessage

from django.contrib.auth.decorators import login_required, permission_required

# from django.contrib import messages

#from django.http import JsonResponse
#from django.views.decorators.http import require_POST
from django.contrib import messages

from django.db.models import Q


def welcome(request):
    return render(request, 'post/welcome.html')

@login_required
def create_post(request):

    posts = Post.objects.all()

    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            posts = form.save(commit=False)
            posts.user = request.user
            posts.save()
            return redirect('post:wall', posts.user.id)
    else:
        form = PostForm()
    if "text" in request.GET:
        return render(request, 'post/content/text.html', {'posts': posts, 'form': form})
    if "image" in request.GET:
        return render(request, 'post/content/image.html', {'posts': posts, 'form': form})
    if "video" in request.GET:
        return render(request, 'post/content/video.html', {'posts': posts, 'form': form})

def update_post(request,post_id):
    post = Post.objects.get(id=post_id)
    if request.method == 'POST' and post.author == request.user:
        form = PostForm(request.POST,files=request.FILES, instance=post)
        if form.is_valid():
            post.save()
            messages.success(request, 'Post has been updated')

        return redirect('post:wall')
    else:
        form = PostForm(instance=post)
    if "text" in request.GET:
        return render(request, 'post/content/text.html', {'posts': post, 'form': form})
    if "image" in request.GET:
        return render(request, 'post/content/image.html', {'posts': post, 'form': form})
    if "video" in request.GET:
        return render(request, 'post/content/video.html', {'posts': post, 'form': form})

def delete_post(request,post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    messages.success(request, 'Post has been deleted')
    return redirect('post:home')


def post_list(request, user_id=None):
    profile = get_object_or_404(Profile, user=request.user)
    friends = profile.friends.all()
    posts = Post.objects.filter(Q(user__in=friends) | Q(user=request.user))
    # print(posts.values())

    if user_id:
        user = User.objects.get(id=user_id)
        posts = Post.objects.filter(user=user).order_by('-created')
        #print(posts.values())
 
   
    all_profiles = Profile.objects.all().exclude(user=profile.user)
    profiles = profile.get_all_friends()

    vv = [friend for friend in profiles]
    print(vv)

    ll = [h.friends.all().exclude(user=profile.user) for h in vv]
    print(ll)

    nn = [item for sublist in ll for item in sublist]
    print(nn)
    
    dup = {i:nn.count(i) for i in nn}
    print(dup)
    # dup = [nn.count(i) for i in nn]
    # print(dup)



    rel_r = Relationship.objects.filter(sender=profile)
    rel_s = Relationship.objects.filter(receiver=profile)
    rel_receiver = []
    rel_sender = []
    for r in rel_r:
        rel_receiver.append(r.receiver.user)
 
    for s in rel_s:
        rel_sender.append(s.sender.user)
   
    nb_invitation = len(rel_sender)
    # print(nb_invitation)
    # print(rel_sender)
    # print(rel_receiver)
    # print(rel_s)
    # print(rel_r)
    return render(request,'post/list.html',{
        'profile':profile,'profiles':profiles,'all_profiles':all_profiles,'posts': posts,'dup':dup,
        'rel_sender':rel_sender,'rel_receiver':rel_receiver,'nb_invitation':nb_invitation})



def post_detail(request, post_id=None):
    post = None
    post = get_object_or_404(Post, id=post_id)
    #print(post)
    comments = Comment.objects.filter(post=post)

    users_like = post.users_like.all()
    #print(users_like)

    if "like" in request.GET : 
        post.users_like.add(request.user)
        return redirect(request.META.get('HTTP_REFERER'))

    
    if "unlike" in request.GET:
        post.users_like.remove(request.user)
        return redirect(request.META.get('HTTP_REFERER'))

    if request.method == 'POST' and request.user.is_authenticated:

        form = CommentForm(data=request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.post = post
            comments.commenter = request.user
            comments.save()
            #print(comments.id)
            return redirect('post:post_detail', post.id)
    else:
        form = CommentForm()
    return render(request, 'post/detail.html', {'post': post, 'form': form, 'comments': comments, 'users_like': users_like})


def update_comment(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, post=post, id=comment_id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
        return redirect('post:post_detail', post.id)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'post/detail.html', {'form': form, 'comment': comment, 'post': post})


def delete_comment(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, post=post, id=comment_id)
    comment.delete()
    return redirect('post:post_detail', post.id)


def register(request):
    if request.method == 'POST':
        form = UserCreationEmailForm(data=request.POST)
        if form.is_valid():
            form.save()
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password1'])
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('post:home')
    else:
        form = UserCreationEmailForm()
    return render(request, 'users/registration.html', {'form': form})

@login_required
def edit(request):
    if request.method == 'POST':
        form = UserEditForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
        return redirect('home')
    else:
        form = UserEditForm(instance=request.user)
    return render(request,'users/edit.html',{'form': form})


def search(request):
    result = User.objects.filter(username__contains=request.GET['name'])
    return render(request, 'post/search.html', {'result': result})

    
@login_required
def send_invitation(request):
    if request.method=='POST':
        id = request.POST.get('profile_id')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(id=id)
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))  # to stay on the same page
    return redirect('post:home')

@login_required
def cancel(request):
    if request.method=="POST":
        id = request.POST.get('profile_id')
        sender = Profile.objects.get(user=request.user)
        receiver = Profile.objects.get(id=id)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('post:home')

@login_required
def reject(request):
    if request.method=="POST":
        id = request.POST.get('profile_id')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(id=id)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('post:home')

@login_required
def accept(request):
    if request.method=="POST":
        id = request.POST.get('profile_id')
        sender = Profile.objects.get(id=id)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            sender.friends.add(receiver.user)
            receiver.friends.add(sender.user)
            rel.save()
    return redirect('post:home')

@login_required
def unfriend(request):
    if request.method=='POST':
        id = request.POST.get('profile_id')
        user = request.user
        sender = Profile.objects.get(user=user)
        print(sender)
        receiver = Profile.objects.get(id=id)
        print(receiver)
        rel = Relationship.objects.get((Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender)))
        #rel = get_object_or_404(Relationship,sender=receiver,receiver=sender)
        print(rel)
        sender.friends.remove(receiver.user)
        receiver.friends.remove(sender.user)
        rel.delete()
        
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('post:home')

post/templates/post/base.html
{% load static %}


<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
    integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/post.css' %}">
  <link rel="shortcut icon" type="image/png" href="" />
  <link rel="shortcut icon" type="image/png" href="{% static 'image/logo.png' %}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>Socialnit</title>



</head>

<body class="body">
  <nav class="navbar navbar-expand-md navbar-light ">
    {% if user.is_authenticated %}
    <a href="{% url 'post:home' %}" class="navbar-brand text-danger"><i class="fas fa-share-alt-square fa-2x" style="color: #87a6fa"></i></a>

      <a class="nav-link text-light  font-weight-bold p-1" href="{% url 'post:home' %}"><h4> The Socialnit</h4></a>

    <form class="form-inline ml-3" action="{% url 'post:search' %}", method="GET">
      <div class="input-group" id="searchz">
        <input type="text" name="name" class="form-control" placeholder="Search">
        <div class="input-group-append">
          <button type="submit" class="btn btn-none" ><i class="fas fa-search" style="color: #abd8dd"></i></button>
        </div>
      </div>
    </form>
    {%else%}
    <a href="{% url 'login' %}" class="navbar-brand text-danger"><i class="fas fa-share-alt-square fa-2x" style="color: #87a6fa"></i></a>

    <a class="nav-link text-light  font-weight-bold p-1" href="{% url 'login' %}"><h4> The Socialnit</h4></a>

  <form class="form-inline ml-3" action="{% url 'post:search' %}", method="GET">
    <div class="input-group" id="searchz">
      <input type="text" name="name" class="form-control" placeholder="Search">
      <div class="input-group-append">
        <button type="submit" class="btn btn-none" ><i class="fas fa-search" style="color: #abd8dd"></i></button>
      </div>
    </div>
  </form>
    {%endif%}
  </nav>

  {% block content %}
  {% endblock %}


</body>

</html>

post/templates/post/create.html
{% extends 'post/base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
CONTACT
{% endblock %}

{% block content %}


<div class="col-md-6 ">
  <div class="container">
  <div class="row justify-content-center mt-3">
      <div class="col-12 col-md-6 col-lg-6 pb-4">
          {%if profile.get_count_friends > 0 %}
              you have {{profile.get_count_friends}} friend{{profile.get_count_friends|pluralize}}:
              <br>
              {%for friend in profiles%}
                  {{friend}}
                  <br>
              {%endfor%}
          {%endif%}
      </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center mt-3">
      <div class="col-12 col-md-6 col-lg-6 pb-4">
              list of all users:
              <br>
             
              <br>
              {%for profile in all_profiles%}
                  {{profile.user}}

                  <br>
                  {% if profile.user not in rel_receiver and profile.user not in rel_sender and profile.user not in profile.friends.all%}
                  <form action="{% url 'post:send_invitation' %}" method="post">
                      {%csrf_token%}
                      <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                          <button type="submit">add to friends</button>                        
                  </form>
                  {%endif%}
                  <br>
                  {% if profile.user in rel_receiver and request.user not in profile.friends.all %}
                          waiting approuval
                          <form action="{% url 'post:cancel' %}" method="post">
                              {%csrf_token%}
                              <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                                  <button type="submit">cancel</button>                        
                          </form>
                          {%endif%}
                  {% if profile.user in rel_sender and request.user not in profile.friends.all %}
                  you have {{nb_invitation}} invitation{{nb_invitation|pluralize}}
                  <form action="{% url 'post:accept' %}" method="post">
                      {%csrf_token%}
                      <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                          <button type="submit">accept</button>                        
                  </form>
                  <br>
                  <form action="{% url 'post:reject' %}" method="post">
                      {%csrf_token%}
                      <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                          <button type="submit">reject</button>                        
                  </form>
                  {%endif%}
                 
                  
                  <br>
                  {% if request.user in profile.friends.all %}
                  <form action="{% url 'post:unfriend' %}" method="post">
                      {%csrf_token%}
                      <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                          <button type="submit">Unfriend</button>                        
                  </form>
                  {%endif%}
                  <br>
              {%endfor%}
      </div>
  </div>
</div>



{% endblock %} 

post/templates/post/list.html
{% extends "post/base.html" %}
{% load static %}
{% load embed_video_tags %}


{% block title %}My Blog{% endblock %}

{% block content %}


{% if user.is_authenticated %}

<h3 class="p-2">Welcome {{user.username}} </h3>
<div class="row" >

  <div class="col-md-3">
    <ul class="nav flex-column" >
      </li>
            

         
      <li><a class="dropdown-item " id="hovhov" href="{% url 'post:wall' user.id%}"> <i class="fas fa-sign-out-alt"></i>my
          wall</a></li>
          <br>
            <li><a class="dropdown-item" id="hovhov" href="{% url 'post:edit' %}"><b>{{ request.user.username }}</b>'s info </a></li>
            <br>
            <li><a class="dropdown-item " id="hovhov" href="{% url 'password_change' %}"> <i class="fas fa-exchange-alt"></i> Change Password</a></li>
            <br>
            <li><a class="dropdown-item " id="hovhov" href="{% url 'logout' %}"> <i class="fas fa-sign-out-alt"></i> Log Out</a></li>
  
          </ul>
          <br>
          <div class="container">
            <p class="pl-2 " id="hovhov" href=""> <i class="fas fa-list"></i> List of all users :</p>
            {%for profile in all_profiles%}
            {% if profile.user not in rel_receiver and profile.user not in rel_sender and profile.user not in profile.friends.all%}
          <form action="{% url 'post:send_invitation' %}" method="post">
              {%csrf_token%}
              <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                  <button type="submit" class="btn" and style="background-color:transparent">
                    <i class="fas fa-plus"> add {{profile.user}}</i>
                  </button>                        
          </form>
          {%endif%}
          {%endfor%}
          </div>
          
    
  </div>


<div class="col-md-6 ">
<div class="form-group">
  <div class="input-group text-center nav-fill w-100">

      <a class="nav-link text-dark  font-weight-bold px-3" href="{% url 'post:create_post' %}?text">
        <button type="button" class="btn btn-primary btn-lg">say something </button>
      </a>

      <a class="nav-link text-dark  font-weight-bold px-3" href="{% url 'post:create_post' %}?image">
        <button type="button" class="btn btn-primary btn-lg">post an image <i class="fas fa-image"></i></button>
      </a>

      <a class="nav-link text-dark  font-weight-bold px-3" href="{% url 'post:create_post' %}?video">
        <button type="button" class="btn btn-primary btn-lg">post a video <i class="fas fa-video"></i></i></button>
      </a>
 
  </div>
</div>






{% for post in posts %}
<div class="container">
  <div class="row">
    <div class="col-9 mx-auto col-md-6 col-lg-12">
      <div class="card mb-2" style="border-color: transparent; background: #dfdff1">

        <div class="p-2">
          <a class="text-decoration-none text-dark" href="{% url 'post:wall' post.user.id %}">
          </a>
        </div>
        <div class="p-1">
          <a class="text-decoration-none text-dark" href="{{post.get_absolute_url}}">
            <h6 class="card-img-top ">&nbsp;&nbsp; {{ post.created }}</h6>
          </a>
        </div>

        {% if request.user not in post.users_like.all %}
          <a href="{% url 'post:post_detail' post.id %}?like"> <i class="fas fa-thumbs-up text-danger p-1"> Like </i></a>
        {% else %}
          <a href="{{post.get_absolute_url}}?unlike"> <i class="fas fa-thumbs-down text-secondary p-1"> Unlike</i></a>
        {% endif %}
        
          
    

        {%if post.text%}
        <div class="p-4">
          <a class="text-decoration-none text-dark" href="{{post.get_absolute_url}}">
            <h3 class="card-img-top" width='600'>{{ post.text }}</h3>
          </a>
        </div>
        {% endif %}
        {%if post.image%}
        <div class="p-4">
          <a class="text-decoration-none text-dark" href="{{post.get_absolute_url}}">
            <h1 class="card-img-top "> <img width='600'  src="{{ post.image.url }}" alt=""> </h1>
          </a>
        </div>
        {% endif %}
        {%if post.video and not post.url %}
        <div class="p-4">
          <a class="text-decoration-none text-dark" href="{{post.get_absolute_url}}"> 
            <video width='600' controls  >
              <source src='{{ post.video.url }}' type='video/mp4'>           
            </video>
          </a>
        </div>
        {% endif %}
        {%if post.url and not post.video%}
        <div class="p-4">
          <a class="text-decoration-none text-dark" href="{{post.get_absolute_url}}">

             {% video post.url '600x400' %}

          </a>
        </div>
        {% endif %}
        {%if post.user == request.user%}
        {%if post.text and not post.video and not post.image%}
        <h6 id="comment"><a  href="{%url 'post:update_post' post.id%}?text" class="text-decoration-none  "><i class="fas fa-edit pt-2"></i> update description</a>&nbsp;&nbsp;
          {%endif%}
          {%if post.image%}
        <h6 id="comment"><a  href="{%url 'post:update_post' post.id%}?image" class="text-decoration-none  "><i class="fas fa-edit pt-2"></i> update</a>&nbsp;&nbsp;
          {%endif%}
          {%if post.video%}
        <h6 id="comment"><a  href="{%url 'post:update_post' post.id%}?video" class="text-decoration-none  "><i class="fas fa-edit pt-2"></i> update</a>&nbsp;&nbsp;
          {%endif%}
          {%if post.url%}
        <h6 id="comment"><a  href="{%url 'post:update_post' post.id%}?url" class="text-decoration-none  "><i class="fas fa-edit pt-2"></i> update</a>&nbsp;&nbsp;
          {%endif%}
          <a href="{%url 'post:delete_post' post.id%}" class="text-decoration-none"><i class="fas fa-trash-alt"></i> delete </a></h6>
        {% endif %}
        <br>

        <h6>&nbsp; Comments: {{post.comments.count}} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Likes:{{post.users_like.count}}</h6>
        <a href="{{post.get_absolute_url}}" class="text-decoration-none"><h6>&nbsp;&nbsp; add a comment</h6></a>
        {%for c in post.comments.all|slice:'2' %}

        <h6 class="font-weight-bold mb-0 text-secondary" style="margin-left: 20px;" >
                          
          
      
        <h5 class="text-dark  mb-0 pt-1 mb-2" style="margin-left: 20px;">
          <i> <span class="mr-1"></span> {{ c.content }}</i></h5>
          <h6 class="date text-secondary">
            <i>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ c.created }} by <u>{{ c.commenter }}</u></i>
           </h6>
       
        {% endfor %}        
        <a href="{{post.get_absolute_url}}" class="text-decoration-none"><h6>&nbsp;&nbsp; view comments</h6></a>
       
      </div>
    </div>
  </div>
</div>

{% endfor %}
</div>





<div class="col-md-3 ">
  <div class="container">
  <div class="">
      <div class="">
      
        
        {%for p in dup|slice:'3' %} 
        {%if p.user not in profiles and p.user not in rel_receiver and p.user not in rel_sender %}
        <p class="p-0"><u> you may know : </u></p> 
        <form action="{% url 'post:send_invitation' %}" method="post" class="p-0">
          {%csrf_token%}
          <input type="hidden" name="profile_id" id="" value="{{p.id}}" >
              <button type="submit" class="btn" and style="background-color:transparent">
                <i class="fas fa-plus"> add {{p}}</i>
              </button>                        
        </form>
        {%endif%} 
        {% endfor %} 
    
        <br>
          {%if profile.get_count_friends > 0 %}
            <u>You have {{profile.get_count_friends}} friend{{profile.get_count_friends|pluralize}}:</u>  
              <br>
              {%for friend in profiles%}
              <a class="text-primary" href="{% url 'post:wall' friend.id %}"><b><i>{{friend}}</i></b> </a>
                  <form action="{% url 'post:unfriend' %}" method="post">
                    {%csrf_token%}
                    <input type="hidden" name="profile_id" id="" value="{{friend.id}}" >
                        <button type="submit" class="btn text-danger" and style="background-color:transparent"><b>Unfriend?</b></button>                        
                </form>
                  <br>
              {%endfor%}
          {%endif%}
      </div>
  </div>

        {%for profile in all_profiles%}
        {% if profile.user in rel_sender and request.user not in profile.friends.all %}
        
       <u>{{profile.user}} sent you an invitation :</u> 

        <form action="{% url 'post:accept' %}" method="post">
            {%csrf_token%}
            <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
            
                <button type="submit" class="btn text-success" and style="background-color:transparent"><b>accept</b> </button>                        
        </form>
        
        <form action="{% url 'post:reject' %}" method="post">
            {%csrf_token%}
            <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                <button type="submit" class="btn text-secondary" and style="background-color:transparent"><b>reject</b> </button>                        
        </form>
        {%endif%}
       
        {%endfor%}
        {%for profile in all_profiles%}
        {% if profile.user in rel_receiver and request.user not in profile.friends.all %}
               <p><b>waiting for <i>{{profile.user}}</i> 's approuval</b> </p> 
                <form action="{% url 'post:cancel' %}" method="post">
                    {%csrf_token%}
                    <input type="hidden" name="profile_id" id="" value="{{profile.id}}" >
                        <button type="submit" class="btn text-danger" and style="background-color:transparent"><b>cancel invitation to {{profile.user}}? </b> </button>                        
                </form>
                {%endif%}
          {%endfor%}
          
             

      </div>
  </div>
</div>


{% endif %}
{% endblock %}